//@version=4
//@author=TradingView
study(title="SMI Ergodic Indicator", shorttitle="SMII", format=format.price, precision=4, resolution="")
longlen = input(20, minval=1, title="Long Length")
shortlen = input(5, minval=1, title="Short Length")
siglen = input(5, minval=1, title="Signal Line Length")
erg = tsi(close, shortlen, longlen)
sig = ema(erg, siglen)
plot(erg, color=#0094FF, title="SMI")
plot(sig, color=#FF6A00, title="Signal")